# ==========================================
# ignore due to wasm incompatibility
# [cov_sv_publisher]
# name = "Fuel Streams Publisher Coverage Analysis"
# packages = [
#     "sv-publisher"
# ]
# all-features = true
# run-types = [
#     "Tests"
# ]
# timeout = "120s"
# color = "Always"
# locked = true
# count = true
# no-dead-code = true
# fail-immediately = true
# skip-clean = true
# engine = "Llvm"
#fail-under = 80

# ==========================================
[cov_fuel_streams_tests]
all-features = true
color = "Always"
count = true
engine = "Llvm"
fail-immediately = true
locked = true
name = "Fuel Data Systems Tests Coverage Analysis"
no-dead-code = true
packages = ["streams-tests"]
run-types = ["Lib", "Tests"]
skip-clean = true
timeout = "120s"
#fail-under = 80

# ==========================================
[report]
out = ["Html", "Xml"]
output-dir = "./cov-reports"
