{{- if .Values.config.createRoles -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  {{- include "k8s.metadata" (dict "context" . "suffix" "-secret-creator") | nindent 2 }}
  labels:
    {{- include "fuel-streams.labels" . | nindent 2 }}
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
- apiGroups: [""] # "" indicates the core API group
  resources: ["secrets"]
  verbs: ["get", "watch", "list", "create", "delete"]
- apiGroups: [""] # "" indicates the core API group
  resources: ["configmaps"]
  verbs: ["get", "watch", "list", "create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  {{- include "k8s.metadata" (dict "context" . "suffix" "-secret-creator") | nindent 2 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "fuel-streams.serviceAccountName" . }}
roleRef:
  kind: Role # this must be Role or ClusterRole
  name: {{ include "fuel-streams.fullname" . }}-secret-creator
  apiGroup: rbac.authorization.k8s.io
{{- end -}}
