[package]
name = "fuel-streams-types"
description = "Types for fuel streams"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[features]
default = []
test-helpers = ["fuel-core/test-helpers"]

[dependencies]
apache-avro.workspace = true
chrono.workspace = true
derive_more.workspace = true
fuel-core.workspace = true
fuel-core-client.workspace = true
fuel-core-types.workspace = true
fuel-data-parser.workspace = true
hex.workspace = true
rand.workspace = true
serde.workspace = true
serde_json.workspace = true
sqlx.workspace = true
tai64 = { version = "=4.0.0", features = ["serde"] }
thiserror.workspace = true
utoipa.workspace = true
voca_rs = "1.15.2"

[dev-dependencies]
pretty_assertions.workspace = true
serde_urlencoded.workspace = true
