apiVersion: 1

# Datasource list
datasources:
  # First Datasource (Prometheus, Default)
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: 5s
    version: 1
    orgId: 1
    uid: "DS__PROMETHEUS"
