apiVersion: v2
appVersion: "1.0"
description: A Helm chart for Kubernetes
name: fuel-local
version: 0.2.0
dependencies:
  - name: fuel-streams-publisher
    version: "0.4.7"
    repository: "file://../fuel-streams-publisher"
  - name: fuel-nats
    version: "0.1.1"
    repository: "file://../fuel-nats"
